config/routes.rb
Rails.application.routes.draw do
  root 'denuncias#index'
  
  resources :contactos
  resources :denuncias
  
end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
    
    has_many :denuncias, dependent: :destroy
end

app/models/denuncia.rb
class Denuncia < ActiveRecord::Base
    belongs_to :contacto
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contactos_controller.rb
class ContactosController < ApplicationController
    
    before_action :find_contacto, only: [:show, :edit, :update, :destroy]
    
    def index
        @contactos = Contacto.all
    end
    
    def show
    end
    
    def new
        @contacto = Contacto.new
    end
    
    def create
        @contacto = Contacto.new(contacto_params)
        
        respond_to do |format|
            if @contacto.save
                format.html { redirect_to contactos_path, :flash => { :success => 'Contacto creado exitosamente.' } }
                format.json { render :show, status: :created, location: @contacto }
            else
                format.html { render 'new', :flash => { :danger => 'Hubo un error al tratar de crear el contacto.' } }
                format.json { render json: @contacto.errors, status: :unprocessable_entity }
            end
        end
    end
    
    def edit
    end
    
    def update
        respond_to do |format|
            if @contacto.update(contacto_params)
                format.html { redirect_to contactos_path, :flash => { :success => 'Contacto editado exitosamente.' } }
                format.json { render :show, status: :updated, location: @story }
            else
                format.html { render :edit, :flash => { :danger => 'Hubo un error al tratar de editar el contacto.' } }
                format.json { render json: @contacto.errors, status: :unprocessable_entity }
            end
        end
    end
    
    def destroy
        respond_to do |format|
            @contacto.destroy
            format.html { redirect_to contactos_path, :flash => { :success => 'Contacto eliminado exitosamente.' } }
            format.json { redirect_to contactos_path, status: :destroyed, location: @contacto }
        end
    end
    
    private
        
        def find_contacto
            @contacto = Contacto.find(params[:id])
        end
    
        def contacto_params
           params.require(:contacto).permit(:nombre_completo, :telefono, :movil, :email, :direccion) 
        end
end

app/controllers/denuncias_controller.rb
class DenunciasController < ApplicationController

    before_action :find_denuncia, only: [:show, :edit, :update, :destroy]
    
    def index
        @denuncias = Denuncia.all
        
        @hash = Gmaps4rails.build_markers(@denuncias) do |denuncia, marker|
            marker.lat denuncia.latitud
            marker.lng denuncia.longitud
            marker.infowindow denuncia.descripcion
            
        end
        
        respond_to do |format|
            format.html {}
            format.json { render json: @hash.to_json } 
        end
    end
    
    def new
        @denuncia = Denuncia.new
    end
    
    def create
        @denuncia = Denuncia.new(denuncia_params)
        
        respond_to do |format|
            if @denuncia.save
                format.html { redirect_to denuncias_path, :flash => { :success => 'Denuncia creada exitosamente.' } }
                format.json { render :show, status: :created, location: @denuncia }
            else
                format.html { render 'new', :flash => { :danger => 'Hubo un error al tratar de crear la denuncia.' } }
                format.json { render json: @denuncia.errors, status: :unprocessable_entity }
            end
        end
    end
    
    def edit
    end
    
    def update
       respond_to do |format|
            if @denuncia.update(denuncia_params)
                format.html { redirect_to denuncias_path, :flash => { :success => 'Denuncia editada exitosamente.' } }
                format.json { render :show, status: :updated, location: @denuncia }
            else
                format.html { render :edit, :flash => { :danger => 'Hubo un error al tratar de editar la denuncia.' } }
                format.json { render json: @denuncia.errors, status: :unprocessable_entity }
            end
        end 
    end
    
    def destroy
       respond_to do |format|
            @denuncia.destroy
            format.html { redirect_to denuncias_path, :flash => { :success => 'Contacto eliminado exitosamente.' } }
            format.json { redirect_to denuncias_path, status: :destroyed, location: @denuncia }
        end 
    end
    
    private
        
        def find_denuncia
            @denuncia = Denuncia.find(params[:id])
        end
        
        def denuncia_params
            params.require(:denuncia).permit(:descripcion, :latitud, :longitud, :contacto_id)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/denuncias_helper.rb
module DenunciasHelper
end

app/views/contactos/_form.html.haml
= form_for @contacto do |f|

    .form-group
        = f.label :nombre_completo
        = f.text_field :nombre_completo, class: 'form-control'

    .form-group
        = f.label :movil
        = f.text_field :movil, class: 'form-control'
        
    .form-group
        = f.label :email
        = f.email_field :email, class: 'form-control'

    .form-group
        = f.submit ( f.object.new_record? ? "Crear Contacto" : "Guardar Cambios"), class: 'btn btn-success'
        = link_to 'Cancelar', :back, class: 'btn btn-default'

app/views/contactos/edit.html.haml
%h2 Editar Contacto

= render 'form'

app/views/contactos/index.html.haml
.col-md-
%h2 Contactos

.row
    .col-md-12
        = link_to new_contacto_path, class: 'btn btn-primary btn-xs' do
            %span.glyphicon.glyphicon-plus
            Crear Nuevo Contacto

%br
        
.row
    .col-md-12
        
        %table.table.table-striped.table-hover
            %thead
                %th ID
                %th Nombre
                %th E-Mail
                %th Movil
                %th
                
            %tbody
                - @contactos.each do |contacto|
                    %tr
                        %td= contacto.id
                        %td= contacto.nombre_completo
                        %td= contacto.email
                        %td= contacto.movil
                        %td
                            = link_to [:edit, contacto], class: 'btn btn-default btn-xs' do
                                %span.glyphicon.glyphicon-pencil
                            = link_to contacto_path(contacto), method: :delete, class: 'btn btn-danger btn-xs' do
                                %span.glyphicon.glyphicon-trash
                            
                        
                        
                        

app/views/contactos/new.html.haml
%h2 Crear Contacto

= render 'form'

app/views/contactos/show.html.haml
%h2 Contacto

%p
    %strong ID:
    = @contacto.id

%p
    %strong E-mail:
    = @contacto.email

%p
    %strong Direccion:
    = @contacto.direccion

app/views/denuncias/_form.html.haml
= form_for @denuncia do |f|

    .form-group
        = f.label :descripcion
        = f.text_field :descripcion, class: 'form-control'
        
    .form-group
        = f.label :latitud
        = f.text_field :latitud, class: 'form-control'
    
    .form-group
        = f.label :longitud
        = f.text_field :longitud, class: 'form-control'
        
    .form-group
        = f.submit 'Crear Denuncia', class: 'btn btn-success'
        = link_to 'Cancelar', :back, class: 'btn btn-default'

app/views/denuncias/edit.html.haml
%h3 Editar Denuncia

= render 'form'

app/views/denuncias/index.html.haml
.row
    .col-md-8
        %h3
        %div{ id: "basic_map", style: 'height: 450px;', class: 'thumbnail' }
    
    .col-md-4
        %h3 
            Denuncias
            .pull-right
                = link_to new_denuncia_path, class: 'btn btn-primary btn-xs' do
                    %span.glyphicon.glyphicon-plus
                    Crear Denuncia
        
        %ul.list-group
            - @denuncias.each do |denuncia|
                %li.list-group-item{ "data-toggle" => "tooltip", "data-placement" => "top", :title => "#{denuncia.latitud} #{denuncia.longitud}" }
                    %span.glyphicon.glyphicon-exclamation-sign
                    = denuncia.descripcion
                    
                    .pull-right
                        = link_to [:edit, denuncia], class: 'btn btn-default btn-xs' do
                            %span.glyphicon.glyphicon-pencil
                        
                        = link_to denuncia_path(denuncia), method: :delete, class: 'btn btn-danger btn-xs' do   
                            %span.glyphicon.glyphicon-trash


    

:javascript
    $('[data-toggle="tooltip"]').tooltip()

    $(document).on('ready page:load', function () {
    //$(function() {
    
        
        
        handler = Gmaps.build('Google');
        handler.buildMap({
            provider: {
              // pass in other Google Maps API options here
              zoom: 0
            },
            internal: {
              id: 'basic_map'
            }
        },
        
          function(){
            
            var markers = handler.addMarkers(#{raw @hash.to_json });  
            
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
          }
        );
    });

app/views/denuncias/new.html.haml
%h2 Crear Denuncia

= render 'form'

app/views/layouts/_alerts.html.haml
- flash.each do |name, msg|
    - if name == "alert"
        = content_tag(:div, msg, class: "alert alert-danger alert-dismissable")
    - elsif name == "notice"
        = content_tag(:div, msg, class: "alert alert-success alert-dismissable")
    - else
        = content_tag :div, msg, class: "alert alert-#{name} alert-dismissable"

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default.navbar-static-top{role: "navigation"}
    .container

        / Brand and toggle get grouped for better mobile display
        .navbar-header
            %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", type: "button"}
                %span.sr-only Toggle navigation
                %span.icon-bar
                %span.icon-bar
                %span.icon-bar
            = link_to root_path, class: 'navbar-brand' do
                %span.glyphicon.glyphicon-tower
                %strong Guardian
        
        / Collect the nav links, forms, and other content for toggling
        .collapse.navbar-collapse.navbar-ex1-collapse
            %ul.nav.navbar-nav
          
            %ul.nav.navbar-nav.navbar-right
                %li
                    = link_to "Denuncias", denuncias_path
                %li
                    = link_to "Contactos", contactos_path
            
                
          
        / /.navbar-collapse

app/views/layouts/application.html.haml
!!! 5

%html
%head
    %title Guardian HN
    
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    
    // BOOTSTRAP
    = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"
    = stylesheet_link_tag 'https://bootswatch.com/united/bootstrap.min.css'
    = javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js'
    
    // Google Maps
    = javascript_include_tag '//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region='
    = javascript_include_tag '//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js'
    = javascript_include_tag '//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js'
    
    = csrf_meta_tags
    
%body

    // NAVBAR
    = render 'layouts/navbar'

    .container
        .row
            .col-md-12
                .panel.panel-default
                    .panel-body
                        = render 'layouts/alerts'
                        
                        = yield